name: Test Codecov Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: 'something'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # for using node
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'
      #     cache: 'npm'
      # https://bun.sh/guides/runtime/cicd
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.22
      - name: Install dependencies
        run: bun install
      - name: Run lint
        run: bun run lint
      - name: Run tests with coverage
        run: bun run coverage
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
